name: Expressions and Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions and Contexts by @${{github.actor}}, event: ${{github.event_name}}"

jobs:
    using-expressions-and-contexts:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a String' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (true && false) }}
            - name: Contexts
              run: |
                echo "GITHUB:  ${{ toJson(github) }}"
                echo "JOB:  ${{ toJson(job) }}"
                echo "SECRETRS:  ${{ toJson(secrets) }}"
                echo "STEPS:  ${{ toJson(steps) }}"
                echo "RUNNER:  ${{ toJson(runner) }}"

